---
# Download a WAR File to the Tomcat webapps directory to be deployed
- name: Download a WAR File to the Tomcat webapps directory to be deployed
  maven_artifact:
    group_id: in.shan5a6
    artifact_id: myweb
    extension: war
    version: "{{version}}"
    username: "{{nexus_user}}"
    password: "{{nexus_password}}"    
    repository_url: 'http://54.89.230.60/repository/java-releases/'
    dest: "{{tomcat_path}}/webapps/app.war"
    owner: "{{service_account}}"
    group: "{{service_account}}"  

